# Set up a Nene development environment using the conda package manager
name: nene
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10
  - pip
  - make
  - pip:
    - -r env/requirements-build.txt
    - -r env/requirements-style.txt
    - -r env/requirements-test.txt
    - -e .[jupyter]
