# Set up a Nene development environment using the conda package manager
name: nene
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pip
  - make
  - pip:
    - -e .[jupyter,dev,lint]
